[package]
name = "howdy-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
serde_json = "1.0.108"
# nokhwa = {version = "*", features = ["input-v4l", "input-opencv"]}
rscam = "0.5.5"
clap = {version = "4", features = ["derive"]}
dlib-face-recognition = "0.3.2"
